### ISSUE TITLE
App state functions and variables need refactoring

### ISSUE THREAD

**Issue by yulian5** [device-automation-bus/dab-adapter-rs#55]
Looking to resolve issue [#54](https://github.com/device-automation-bus/dab-adapter-rs/pull/54) why Netflix app cannot be resumed I found some code which, I think, needs improvement:

1. There is a function **get_app_state** in **get_state.rs** file but there are also at least three copies of full implementations to get app state in **exit.rs**, **luanch.rs** and **launch_with_content.rs** with multiple strings manipulations beyond that. The suggestion is to have just one function for that purpose to get app state which returns enum value.
2. Boolean variables  **app_created** and **is_suspended** in those files are just emulation of tri-state app status we're getting from RDKShell. To get the correct state of the app the code in general should check both variables at the same time. Missing that creates problems like [#54](https://github.com/device-automation-bus/dab-adapter-rs/pull/54). Adding more apps will complicate logic even more.

The suggestion is to follow Thunder framework and to use enum values for app state and which **get_app_state** will return:
```
pub enum State {
    Stopped,
    Suspended,
    Resumed // or Running
}
```
Ideally DAB states looks better as ( STOPPED, BACKGROUND, FOREGROUND), but FOREGROUND in DAB means resumed, visible, and in focus. RDKShell returning app state "resumed" doesn't assume that app is visible or in focus. Just that the app is running. Visibility and Focus are controlled and retrieved separately. So the code like in **get_state.rs**:
```
            match item.state.as_str() {
                "suspended" => return Ok("BACKGROUND".to_string()),
                _ => return Ok("FOREGROUND".to_string()),
            }

```
is actually incorrect for returning something like FOREGROUND state. It probably works fine with just one app tests (like "YouTube") but with multiple apps it will produce difficult to find deviations.

@arun-madhavan-013 would you like to work on this? If not I can work on this next month.

Thanks!

**Comment by arun-madhavan-013** [comment]
Hi @yulian5 ,

Thanks for spotting it.
Let me take a look.

**Comment by yulian5** [comment]
Completed by [https://github.com/device-automation-bus/dab-adapter-rs/pull/56](https://github.com/device-automation-bus/dab-adapter-rs/pull/56)
